name: Init Main Cache

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  InitMainCache:
    name: Init Main Cache
    runs-on: ubuntu-latest
    steps:
      - name: check for cache
        id: cache-check
        uses: actions/cache@v3
        with:
          lookup-only: true
          path: Library
          key: Library
          restore-keys: |
            main
            
      - name: create folder
        if: ${{ !needs.search.outputs.cache-check }} == 'false'
        run: |
          mkdir -p Library
          
      - name: save cache
        if: ${{ !needs.search.outputs.cache-check }} == 'false'
        uses: actions/cache/save@v3
        with:
          path: Library
          key: Library
          restore-keys: |
            main
