name: Build project

on:
  push:
    branches:
      - main

jobs:
  buildForAndroidPlatform:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - Android
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
          
      - uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          versioning: Semantic
          targetPlatform: ${{ matrix.targetPlatform }}
          # androidExportType: 'androidAppBundle'
          # androidKeystoreName: user.keystore
          # androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          # androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          # androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS }}
          # androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
          customParameters: -BuildOptions CompressWithLz4

      - uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}