name: Cache project

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  CacheTest:
    name: Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Check for cache
        id: cache-check
        uses: actions/cache@v3
        with:
          path: Library
          key: Library
          restore-keys: |
            main
          lookup-only: true
            
      - name: check File
        if: steps.cache-check.outputs.cache-hit != 'true'
        run: |
          echo "false"

      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v3
        with:
          path: Library
          key: Library
          restore-keys: |
            main

      - name: Create File
        run: |
          [ -f Library/test.txt ] && cat Library/test.txt
          mkdir -p Library
          echo "test message" > Library/test.txt

      - name: Save cached Primes
        id: cache-primes-save
        uses: actions/cache/save@v3
        with:
          path: Library
          key: Library