name: Cache project

on:
  push:
    tags:
      - v*

jobs:
  CacheTest:
    name: Cache
    runs-on: ubuntu-latest
    steps:
      - name: Check for cache
        id: cache-check
        uses: actions/cache@v3
        with:
          lookup-only: true
          path: Library
          key: Library
          restore-keys: |
            main
            develop

      - if: steps.cache-check.outputs.cache-hit
        # 들여쓰기 수정
        then:
          - name: Yes Cache
            run: |
              echo "Yes Cache"
      - else:
        # 들여쓰기 수정
        then:
          - name: No Cache
            run: |
              echo "No Cache"

      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache@v3
        with:
          path: Library
          key: Library
          restore-keys: |
            main
            develop
          lookup-only: false

      - name: Create File
        run: |
          [ -f Library/test.txt ] && cat Library/test.txt
          mkdir -p Library
          echo "test message" > Library/test.txt

  # CacheMain:
  #   runs-on: ubuntu-latest
  #   branches:
  #     - main
  #   if: ${{ startsWith(github.event.ref, 'refs/tags/v1.') }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #         lfs: true
  #     - uses: actions/cache@v3
  #       with:
  #         path: Library
  #         key: Library-main
  # - name: Save Primes
  #   id: cache-primes-save
  #   uses: actions/cache/save@v2
  #   with:
  #     path: |
  #       Library
  #     key: Library