name: Cache project

on:
  push:
    tags:
      - v*

jobs:
  CacheTest:
    name: Cache
    runs-on: ubuntu-latest
    steps:
      - name: Check for cache
        id: cache-check
        uses: actions/cache@v3
        with:
          lookup-only: true
          path: Library
          key: Library
          restore-keys: |
            main
            develop
      
      - uses: other-workflow.yml
      # - name: Check if
      #   if: ${{ !needs.search.outputs.cache-hit }} == 'false'
      #   uses: ./other-workflow.yml

      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache@v3
        with:
          path: Library
          key: Library
          restore-keys: |
            main
            develop
          lookup-only: false

      - name: Create File
        run: |
          [ -f Library/test.txt ] && cat Library/test.txt
          mkdir -p Library
          echo "test message" > Library/test.txt