
name: Cache project

on:
  push:
    tags:
      - v*

jobs:
  CacheTest:
    name: Cache
    runs-on: ubuntu-latest
    steps:
      
      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache@v3
        with:
          path: |
            Library
          key: Library    
          restore-keys: |
            main
            refs/tag/*
            develop

      - name: Create File
        run: |
          [ -f Library/test.txt ] && cat Library/test.txt
          mkdir -p Library
          echo "test message" > Library/test.txt

      # - name: Save Primes
      #   id: cache-primes-save
      #   uses: actions/cache/save@v2
      #   with:
      #     path: |
      #       Library
      #     key: Library